# Generated by Django 2.2.19 on 2021-04-09 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0002_pythonpackagecontent_python_version'),
    ]

    operations = [
        migrations.DeleteModel(name="pythonpackagecontent"),
        migrations.CreateModel(
            name='PythonPackage',
            fields=[
                ('pulp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pulp_created', models.DateTimeField(auto_now_add=True)),
                ('pulp_last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(editable=False)),
                ('author', models.TextField()),
                ('author_email', models.TextField()),
                ('bugtrack_url', models.TextField()),
                ('classifiers', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('description', models.TextField()),
                ('description_content_type', models.TextField()),
                ('docs_url', models.TextField()),
                ('download_url', models.TextField()),
                ('home_page', models.TextField()),
                ('keywords', models.TextField()),
                ('license', models.TextField()),
                ('maintainer', models.TextField()),
                ('maintainer_email', models.TextField()),
                ('package_url', models.TextField()),
                ('platform', models.TextField()),
                ('project_url', models.TextField()),
                ('project_urls', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('release_url', models.TextField()),
                ('requires_dist', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('requires_python', models.TextField()),
                ('summary', models.TextField()),
                ('version', models.TextField()),
            ],
            options={
                'unique_together': {('name',)},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PythonPackageContent",
            fields=[
                ('name', models.TextField()),
                ('count', models.IntegerField()),
                ('combined_hash', models.CharField(max_length=64)),
                ('package', models.ForeignKey(related_name="python_pythonpackagecontent",to="python.PythonPackage", on_delete=models.CASCADE, editable=False)),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
                'unique_together': {('name', 'combined_hash')},
            },
            bases=('core.content',),
        ),
    ]
